name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v10
      with:
        version: '3.1.21'
        # no-cache: true
        actions-cache-folder: 'emsdk-cache'
    - uses: actions/setup-node@v2
      with:
        node-version: '16.15.0'
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Linux build
      if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        npm install --legacy-peer-deps
        npm run build --workspaces --if-present

    - name: Test
      run: |
        npm run rebuild -w packages/test
        npm run test -w packages/test

    - name: Test MEMORY64
      env:
        MEMORY64: '1'
      run: |
        npm run rebuild -w packages/test
        npm run test -w packages/test

    - name: Publish
      if: ${{ startsWith(github.event.ref, 'refs/tags') && matrix.os == 'ubuntu-latest' }}
      run: |
        node ./script/release.js
        npm publish --ignore-scripts -w packages/runtime -w packages/emnapi

    - name: Create release
      if: ${{ startsWith(github.event.ref, 'refs/tags') }}
      uses: toyobayashi/upload-release-assets@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.after }}
        release_name: ${{ github.event.after }}
        draft: true
        prerelease: false
        assets: ./script/emnapi.zip
